version: 0.0
os: linux
files:
- source: /
  destination: /var/www/
hooks:
  ApplicationStop:
  - location: stop_server.sh
    timeout: 300
    runas: ubuntu
  BeforeInstall:
  - location: create_root_dir.sh
    timeout: 60
    runas: ubuntu
  AfterInstall:
  - location: install_dependencies.sh
    timeout: 180
    runas: ubuntu
  ApplicationStart:
  - location: start_server.sh
    timeout: 60
    runas: ubuntu
