version: 0.0
os: linux
files:
- source: /artifact
  destination: /var/www/
hooks:
  ApplicationStop:
  - location: stop_server.sh
    timeout: 300
    runas: root
  BeforeInstall:
  - location: create_root_dir.sh
    timeout: 60
    runas: root
  AfterInstall:
  - location: install_dependencies.sh
    timeout: 180
    runas: root
  ApplicationStart:
  - location: start_server.sh
    timeout: 60
    runas: root
