ersion: 0.2

phases:
  install:
    commands:
    - echo Installing source NPM dependencies...
    - npm install
  build:
    commands:
    - echo Build started on `date`
    - tsc
  post_build:
    commands:
    - echo Build completed on `date`

artifacts:
  files:
  - '**/*'
  base-directory: './*'
  discard-paths: yes
