version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
     - echo Install completed on `date`
  pre_build:
    commands:
     - npm install
     - echo Pre Build completed on `date`
  build:
    commands:
     - echo Build started on `date`
     - ls
     - npm run test
     - npm run build
     - echo Build ended on `date`
  post_build:
    commands:
     - mkdir ./dist/scripts/ -p
     - cp -r ./scripts/ ./dist/scripts/
     - cd ./dist
     - ls
     - cd ..
     - echo Post Build completed on `date`

artifacts:
  files:
   - './dist/**/*'
   - 'package.json'
   - 'package-lock.json'
   - 'appspec.yml'
  base-directory: './'
